### ISSUE TITLE
Make urls local in code block

### ISSUE THREAD

**Issue by c3ho** [rubyAnneB/linkReaper-cli#3]
https://github.com/rubyAnneB/linkReaper-cli/blob/55cc85ab3cb2a27df477888de4def9027bb58f3f/linkReaper/linkReaper.py#L73-L93

Hi, noticed you're not using `urls` anywhere else aside from the first conditional, why not make the variable local to that condition only? You can remove line 76 and instead do `urls = [link for link in urls_raw if link not in urls]` <-- untested but it should be something similar at line 82

**Comment by rubyAnneB** [comment]
Thanks for the feedback. I appreciate your help.
